Fix: Add support for nativeTokens/feature in sendAdvanced
iotaledger/iota.lib.js pull request #1039
Opened 2022-11-08 12:48 UTC by msarcev

# Description of change

- Added support for optionally defining nativeTokens and features for outputs in highLevel/sendAdvanced.ts

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-11-08 16:11 UTC, abbasabid requested changes
Is there any reason why these empty validation files have been added?

2022-11-11 14:33 UTC, brancoder requested changes
Remove two added empty validation files.

2022-11-11 14:33 UTC, brancoder commented on packages/iota/src/highLevel/sendAdvanced.ts
> +        fatures?: FeatureTypes[];
We should also add the unlock conditions.

2022-11-11 14:33 UTC, brancoder commented on packages/iota/src/highLevel/sendAdvanced.ts
>                  unlockConditions: [
Looks like the unlock conditions are hardcoded here.  Sending outputs with additional unlock conditions, other than Address unlock condition, will also get discarded. 
Looks like the whole sendAdvanced function needs a refactor :)

2022-11-11 16:49 UTC, brancoder commented on packages/iota/src/highLevel/sendAdvanced.ts
> +        fatures?: FeatureTypes[];
Fix the typo in word `fatures`.

2022-11-14 09:35 UTC, brancoder approved these changes

2022-11-14 09:41 UTC, abbasabid approved these changes

2022-11-14 12:23 UTC, merged