Feat: Update milestone routes
iotaledger/iota.lib.js pull request #849
Opened 2022-04-27 12:37 UTC by brancoder

# Description of change

Update milestone routes according to[ TIP-25](https://github.com/iotaledger/tips/blob/6a926b3028986571eab2b19952c033784b7fd512/tips/TIP-0025/core-rest-api.yaml)
Fixes #848 .

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-28 13:05 UTC, msarcev requested changes

2022-04-28 13:05 UTC, msarcev commented on packages/iota/src/clients/singleNodeClient.ts
> +        return this.fetchBinary(this._basePath, "get", `messages/${messageId}`);
I'm not sure this will work, as API states that it will return data as JSON, and here we interpret it as binary.

2022-04-28 13:05 UTC, msarcev commented on packages/iota/src/clients/singleNodeClient.ts
> +        return this.fetchBinary(this._basePath, "get", `transactions/${transactionId}/included-message`);
Also here, if endpoint returns JSON, we should probably just use `fetchJson`, and remove this version of fetch.

2022-04-28 13:05 UTC, msarcev commented on packages/iota/src/clients/singleNodeClient.ts
> +        return this.fetchBinary(this._basePath, "get", `outputs/${outputId}`);
Same here as comments above.

2022-04-28 13:05 UTC, msarcev commented on packages/iota/src/clients/singleNodeClient.ts
> +        return this.fetchBinary(this._basePath, "get", `milestones/by-index/${index}`);
Also here as in comments about content type.

2022-04-28 13:05 UTC, msarcev commented on packages/iota/src/clients/singleNodeClient.ts
> +        return this.fetchBinary(this._basePath, "get", `milestones/${milestoneId}`);
Also here as in comments about content type.

2022-04-28 13:42 UTC, lzpap commented on packages/iota/src/clients/singleNodeClient.ts
> +            { "Content-Type": "application/vnd.iota.serializer-v1" },
```suggestion
            { "Accept": "application/vnd.iota.serializer-v1" },
```
The response content type is controlled through passing in tyhe accept header, see how it is implemented in hornet: https://github.com/gohornet/hornet/blob/307017aafcfa1c3c13490114c3476b6ddcd17025/pkg/restapi/restapi.go#L100

2022-04-29 09:58 UTC, brancoder commented on packages/iota/src/clients/singleNodeClient.ts
> +        return this.fetchBinary(this._basePath, "get", `messages/${messageId}`);
If "Accept": "application/vnd.iota.serializer-v1" is specified in request the response will be binary data.

2022-04-29 11:57 UTC, lzpap approved these changes

2022-04-29 13:59 UTC, msarcev approved these changes

2022-04-29 14:00 UTC, merged