* Created wiki docs
iotaledger/iota.lib.js pull request #924
Opened 2022-07-08 16:53 UTC by lucas-tortora

# Description of change

* Created wiki docs
* Added wiki build system
* Created sections based on iota-ledger/docs-template
* Added script to all the packages package.json to generate API ref for the wiki
* Added all non-nft examples as how tos
* Created getting started guide
* Created how to run how tos guide.

## Related issues

* Resolves https://github.com/iotaledger/iota.js/issues/916
* Resolves https://github.com/iotaledger/iota.js/issues/917
* Resolves https://github.com/iotaledger/iota.js/issues/918
* Resolves https://github.com/iotaledger/iota.js/issues/919

 
## TODO

-[] Review outputs
-[] Add meta tags
-[]  Add banner

## Type of change

- Documentation Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Docs were built locally.

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2022-07-08 16:54 UTC, lucas-tortora commented
@brancoder , whenever you have a moment, please have a look this :)

2022-07-08 16:56 UTC, lucas-tortora commented
@aleksei-korolev , @Dr-Electron, , whenever you have a moment, please have a look this :)

2022-07-11 10:55 UTC, brancoder commented on documentation/admonitions/_enable_pow.md
> +This example requires an API endpoint that has "Proof of Work" enabled.
Maybe we can remove this admonition because all examples have been updated to use local PoW. [PR](https://github.com/iotaledger/iota.js/pull/926)

2022-07-11 10:55 UTC, brancoder commented on documentation/docs/how_tos/browser.mdx
> +TypeError: client.milestone is not a function
Browser example has been updated an no longer throws this error. [PR](https://github.com/iotaledger/iota.js/pull/926)

2022-07-11 12:45 UTC, aleksei-korolev requested changes
I skipped the /reference/ folder since the files are autogenerated anyway.

2022-07-11 12:45 UTC, aleksei-korolev commented on documentation/admonitions/_iotars.md
> +Tough this library is functionally complete, the [iota.rs](https://wiki.iota.org/iota.rs/welcome) library is maintained
tough

2022-07-11 12:45 UTC, aleksei-korolev commented on documentation/admonitions/_iotars.md
> +will have the all the latest features.
```suggestion
has the latest features.
```

2022-07-11 12:45 UTC, aleksei-korolev commented on documentation/admonitions/_wallet_transaction_recommendation.md
> +[`wallet.rs`](https://wiki.iota.org/wallet.rs/welcome) library together with the
```suggestion
[wallet.rs](https://wiki.iota.org/wallet.rs/welcome) library together with the
```

2022-07-11 12:45 UTC, aleksei-korolev commented on documentation/admonitions/_wallet_transaction_recommendation.md
> +[`stronghold.rs`](https://wiki.iota.org/stronghold.rs/welcome) enclave for value-based transfers. This combination
```suggestion
[stronghold.rs](https://wiki.iota.org/stronghold.rs/welcome) enclave for value-based transfers. This combination
```

2022-07-11 12:45 UTC, aleksei-korolev commented on documentation/docs/contribute.md
> +description: Contribute to the IOTA wiki docs templates by contributing to the official GitHub repository or sharing  your knowledge on Discord.
```suggestion
description: Contribute to the IOTA wiki docs templates by contributing to the official GitHub repository or sharing your knowledge on Discord.
```

2022-07-11 12:45 UTC, aleksei-korolev commented on documentation/docs/contribute.md
> +image: /img/logo/iota_logo.svg
svg images don't work AFAIK

2022-07-11 12:45 UTC, aleksei-korolev commented on documentation/docs/getting_started.mdx
> +import IotaRS from '../admonitions/_iotars.md'
Article metadata is missing across multiple files

2022-07-11 12:45 UTC, aleksei-korolev commented on documentation/docs/how_tos/data.mdx
> +Retrieveing Data
Retrieveing, probably needs to be fixed in the code snippet, too.

2022-07-11 12:45 UTC, aleksei-korolev commented on documentation/docs/references/client/classes/B1T6.md
> +# Class: B1T6
Since this all is autogenerated, we could look into it to generate some basic docusaurus metadata like keywords.

2022-07-11 13:30 UTC, lucas-tortora commented on documentation/docs/contribute.md
> +image: /img/logo/iota_logo.svg
they don't I need to pdate all the meta tags

2022-07-11 13:31 UTC, lucas-tortora commented on documentation/docs/getting_started.mdx
> +import IotaRS from '../admonitions/_iotars.md'
yup, It's on the `todo` list in the PR draft description, I'll get to them today, but I though it'd be good to get a head start on the articles

2022-07-11 14:11 UTC, lucas-tortora commented on documentation/admonitions/_iotars.md
> +Tough this library is functionally complete, the [iota.rs](https://wiki.iota.org/iota.rs/welcome) library is maintained
```suggestion
Though this library is functionally complete, the [iota.rs](https://wiki.iota.org/iota.rs/welcome) library is maintained
```

2022-07-11 19:34 UTC, lucas-tortora commented on documentation/docs/references/client/classes/B1T6.md
> +# Class: B1T6
done, though if we plan on using type-docs everywhere I think we should work on a custom theme to add these

2022-07-14 13:54 UTC, brancoder commented on documentation/docs/contribute.md
> +  .
Extra space between link and the dot.

2022-07-14 14:07 UTC, brancoder commented on documentation/docs/contribute.md
> +- [Contribute to the documentation](#contribute-to-the-documentation).
Extra space between link and the dot

2022-07-14 14:07 UTC, brancoder commented on documentation/docs/getting_started.mdx
> +You can find additional usage [examples](https://github.com/iotaledger/iota.js/tree/dev/packages/iota/examples) in the
For the Beta-testnet release should we link to the examples on the feat/stardust branch?

2022-07-14 14:07 UTC, brancoder commented on documentation/docs/getting_started.mdx
> +npm install @iota/iota.js
For the Beta testnet should we add the next tag @iota/iota.js@next. The next tag denotes the latest stardust version

2022-07-14 14:11 UTC, lucas-tortora commented on documentation/docs/contribute.md
> +  .
```suggestion
- [Report a bug](https://github.com/iotaledger/iota.js/issues/new?assignees=&labels=c-bug&template=bug_report.md&title=).
```

2022-07-14 14:15 UTC, brancoder approved these changes

2022-07-15 11:21 UTC, aleksei-korolev approved these changes

2022-07-15 11:21 UTC, aleksei-korolev commented on documentation/docs/contribute.md
> +
```suggestion
```

2022-07-15 13:34 UTC, merged